### ISSUE TITLE
Laravel 8 Support

### ISSUE THREAD

**Issue by HDVinnie** [hidehalo/laravel-view-shrinker#1]
Is Laravel 8 support planned?

**Comment by hidehalo** [comment]
Hi @HDVinnie, thanks for you proposal! 
> Is Laravel 8 support planned?

Personally, I don’t have this plan, but if the community needs it, I’m very happy to implement it.

I will release a new version soon. 😆

**Comment by hidehalo** [comment]
@HDVinnie Since [8.0.0]released, you would get Laravel 8 support. Cheers! 😆
